### ISSUE TITLE
Stop promoting for game developers

### ISSUE THREAD

**Issue by henriiquecampos** [pigdevstudio/organization#1]
They are not our audience, that's it @Keyaki777

**Comment by Keyaki777** [comment]
test

2018-04-07 0:10 GMT-03:00 Henrique Campos <notifications@github.com>:

**Comment by henriiquecampos** [comment]
I think that after the discussion of April's 9th and based on feedback gave in [itch.io community](https://itch.io/t/207911/thoughts-about-business) we can pretty much say this is not a must have.

We will need to take some extra steps tho:

1. Reorient the Patreon's page to be gamedev oriented
2. Design our itch.io page to feature some tools
3. Use our games as marketing tools to feature our products
4. Which will be, initially assets of all kinds
5. After 12~20 games library we can turn back into a gamers/players oriented model
